### ISSUE TITLE
Use fa-ban for the status icon of disabled hosts

### ISSUE THREAD

**Issue by andybraren** [openshift-metal3/facet#231]
Should I use this repo, [facet-lib](https://github.com/mareklibra/facet-lib), Jira, or a Google Doc somewhere to capture little nits like this? 🙂

### Current

![image](https://user-images.githubusercontent.com/9122899/85354599-f1bf4080-b4d8-11ea-902f-68a00972c4f3.png)

### Proposed

Use `fa-ban`, listed [here](https://www.patternfly.org/v4/design-guidelines/styles/icons), for the status icon of disabled hosts. `--pf-global--Color--200` would also be 👌.

![image](https://user-images.githubusercontent.com/9122899/85354963-ab1e1600-b4d9-11ea-93cc-2631f0f2a823.png)

**Comment by mareklibra** [comment]
Tracked in jira, closing here
