### ISSUE TITLE
Two items instead one are highlighted at the navigation pane if we try to navigate between them

### ISSUE THREAD

**Issue by dkholodo** [openshift-metal3/facet#44]
#22 
Steps to reproduce:
1. Fill all required fields at the "1. Cluster setup" section
2. Click Next. Now you should be at the "2. Add hosts" section.
3. Click at the sidebar at a "1. Cluster setup" section or at a "3. Results" section

Expected results:
"2. Add hosts" should not be highlighted anymore in case if it is possible to navigate between sections.
In case if we shouldn't be able to navigate between all sections, all these other sections should be gray out and we shouldn't be able to click on them.

Actual result:
Two sections are highlighted at the same time (please see the screenshot)
![Two items instead one are highlighted at the navigation pane if we try to navigate between them](https://user-images.githubusercontent.com/37401605/54124419-0aeacd80-440b-11e9-9017-134e9d1cba55.jpg)

**Comment by jtomasek** [comment]
Note that this component is just a placeholder for now. We intend to use wizard navigation panel here. The patternfly-next feature has already been merged for it [1], depending on time constraints, we can wait for react component to be implemented in pattefly react.

[1] https://github.com/patternfly/patternfly-next/pull/1404

**Comment by knowncitizen** [comment]
This will probably not be fixed due to Facet being abandoned.
